### ISSUE TITLE
[Recommender] Implements newly added methods

### ISSUE THREAD

**Issue by shiodat** [jubatus/jubakit#126]
I want to use the following methods.

- [similar_row_from_id_and_score](http://jubat.us/ja/api/api_recommender.html#recommender::similar_row_from_id_and_score__s.double)
- [similar_row_from_id_and_rate](http://jubat.us/ja/api/api_recommender.html#recommender::similar_row_from_id_and_rate__s.float)
- [similar_row_from_datum_and_rate](http://jubat.us/ja/api/api_recommender.html#recommender::similar_row_from_datum_and_rate__datum.float)
- [similar_row_from_datum_and_score](http://jubat.us/ja/api/api_recommender.html#recommender::similar_row_from_datum_and_score__datum.double)

**Comment by rimms** [comment]
Fixed via #127
