### ISSUE TITLE
Transforming label key in a Schema definition will cause RuntimeError in extracting a training result with 'in' operator.

### ISSUE THREAD

**Issue by Asayu123** [jubatus/jubakit#134]
# Problem Summary
* If we transform a label key in a Schema definition, it causes RuntimeError in the subsequent training process.
* This RuntimeError will happen if we extract training results via 'in' operator.

# How to reproduce the error
* Install jubakit==0.6.1

## Define a schema with a label for a classifier

```schema.py
EmailSchema = Schema(
    {
        'category': (Schema.LABEL, 'category'), # This transform cause error.
        'subject': (Schema.STRING, 'subject'),
        'body': (Schema.STRING, 'text'),
        'attachment_names': (Schema.STRING, 'attachments'),
    }, fallback=Schema.IGNORE
)
```

## And extract the training result on main.py.

```main.py
...
loader = CustomLoader(data=training_data)
        dataset = Dataset(loader=loader, schema=EmailSchema).shuffle()
        for (idx, label) in self.service.train(dataset):
	  # CAUSE RuntimeError.
...

```

### Crash traceback

```
Traceback (most recent call last):
...
  File "/Users/user/MyAppDir/venv/lib/python3.6/site-packages/jubakit/classifier.py", line 140, in train
    for (idx, (label, d)) in dataset:
  File "/Users/user/MyAppDir/venv/lib/python3.6/site-packages/jubakit/base.py", line 405, in __iter__
    yield (self._index, self._schema.transform(row))
  File "/Users/user/MyAppDir/venv/lib/python3.6/site-packages/jubakit/classifier.py", line 32, in transform
    d = self._transform_as_datum(row, None, [self._label_key])
  File "/Users/user/MyAppDir/venv/lib/python3.6/site-packages/jubakit/base.py", line 198, in _transform_as_datum
    self._add_to_datum(d, key_type, key_name, value)
  File "/Users/user/MyAppDir/venv/lib/python3.6/site-packages/jubakit/base.py", line 180, in _add_to_datum
    raise RuntimeError('invalid type {0} for key {1}'.format(t, k))
RuntimeError: invalid type l for key category
```

# Remarks
* If we don't extract the training result, the error won't happen.

```alternate_main.py
...
loader = CustomLoader(data=training_data)
        dataset = Dataset(loader=loader, schema=EmailSchema).shuffle()
        self.service.train(dataset)  # It will work.
...


```

I'm not sure those behaviors are a bug or intended one, So I opened this issue.
Thank you in advance.

**Comment by shiodat** [comment]
@Asayu123 Thank you for reporting the issue!
I'm going to reproduce the error, would you share the `CustomLoader` source code?
If the amount of source code is large, using https://gist.github.com/ is better than pasting the snippet at this issue.

**Comment by Asayu123** [comment]
Thank you for your quick response!
Following is my CustomLoader Source code.
(I'm trying to implement jubakit to Django project.)

```loader.py
from django.forms.models import model_to_dict
from jubakit.base import BaseLoader


class QuerysetLoader(BaseLoader):
    def __init__(self, queryset, *args, **kwargs):
        self.queryset = queryset
        super().__init__(*args, **kwargs)

    def rows(self):
        for obj in self.queryset:
            yield model_to_dict(obj)
```

**Comment by shiodat** [comment]
@Asayu123 Thanks for sharing the code. The loader is work correctly ;)

The Datum object does not contains the label column because Jubatus classifier fit using (datum, label) pairs.

And the following schema will work with your environment, would you please try it?
```
EmailSchema = Schema(
    {
        'category': Schema.LABEL, # You have to set LABEL schema, not specifying the alternative column name.
        'subject': (Schema.STRING, 'subject'),
        'body': (Schema.STRING, 'text'),
        'attachment_names': (Schema.STRING, 'attachments'),
    }, fallback=Schema.IGNORE
)
```
I checked it works with the `classifier_csv.py` example.

The official document is a bit confusing and I will fix the docs in the next release.

**Comment by Asayu123** [comment]
@shiodat
Thank you for your response,  
I removed the alternative column name from label definition, and confirmed that It works well!

I understood that is expected behavior, and I'm looking forward to seeing the new doc.

I'm glad if you close this issue at your convenience, for example, after you update the doc.

Thank you!

**Comment by shiodat** [comment]
@Asayu123 

Thank you for your comment !
In the next release, I will fix the code to work with your schema definition :)
```
EmailSchema = Schema(
    {
        'category': (Schema.LABEL, 'category'), # This transform cause error.
        'subject': (Schema.STRING, 'subject'),
        'body': (Schema.STRING, 'text'),
        'attachment_names': (Schema.STRING, 'attachments'),
    }, fallback=Schema.IGNORE
)
```

**Comment by Asayu123** [comment]
@shiodat 
Hi, I confirmed that all unit test related to this issue passed after updating jubakit from 0.6.1 to 0.6.2 in my project.

So I'm pretty sure that this issue has resolved entirely.

Thank you for your excellent work!

**Comment by shiodat** [comment]
@Asayu123 Great! If you discover another problems, please open a new issue, thanks!
