### ISSUE TITLE
Missing "clear_row" method in jubakit.Recommender .

### ISSUE THREAD

**Issue by Asayu123** [jubatus/jubakit#136]
# Problem Summary
In official document, there is a clear_row method in jubakit.Recommender, but there is no method in actual implementation. 

# Versions
* jubakit==0.6.1

# Remarks
* I'm not sure whether jubakit supports all method of the client API, but it could be an essential function if we provide a "valid" top N recommendation in actual services.

Thank you in advance. : )

**Comment by Asayu123** [comment]
@shiodat
Hi, I confirmed that a method related to this issue works after updating jubakit from 0.6.1 to 0.6.2 in my project.

Thank you for your excellent work!

**Comment by shiodat** [comment]
@Asayu123 Thanks!
