### ISSUE TITLE
Hard to read version number in docs

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubakit#80]
http://jubat.us/ja/jubakit/index.html
<img width="287" alt="2017-03-17 15 00 16" src="https://cloud.githubusercontent.com/assets/939877/24030847/7931c074-0b22-11e7-9d1c-b5e867c9b428.png">

**Comment by shiodat** [comment]
I make some color combinations of home icon and version number.
Which is the best ? or does anyone have nice ideas?

![jubatus_header](https://cloud.githubusercontent.com/assets/8208713/24035129/9972399e-0b37-11e7-8215-8ba2035383fe.png)

**Comment by shiodat** [comment]
In offline meeting, we decide to use `2. black x black` colors.
We also have to fix https://github.com/jubatus/website home icon color.

**Comment by kmaehashi** [comment]
Fixed via #81
