### ISSUE TITLE
Improve support of bool type

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubakit#9]
Currently, when mapping `bool` type entry to `Schema.NUMBER`, `False` is converted into `0`. However Jubatus ignores `0` feature vectors.  We should consider how to handle `bool` type.

**Comment by kmaehashi** [comment]
As ``bool`` is a categorical value it should map to string value (``"0"``, ``"1"``); I'll work on this.

**Comment by shiodat** [comment]
Fixed via #63.
